config/routes.rb
Rails.application.routes.draw do
 root to: 'tasks#index'
 
 get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :tasks
  
  get 'signup', to: 'users#new'
  resources :users, only: [:new, :create]

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end

# 全てのコントローラで counts(user) が使用できる。users_controllerのshowで使用。
  def counts(user)
    @count_taskss = user.tasks.count
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
    
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # TasksController の全アクションをログイン必須にする。
  before_action :require_user_logged_in
  # edit,update,destroy アクションが実行される前に correct_user が実行される。
  before_action :correct_user, only: [:show, :edit, :update, :destroy]


  def index
      # @task = current_user.tasks.build  # form_with 用
      @tasks = current_user.tasks.order(id: :desc).page(params[:page]).per(5)
  end
  
  def show
    # @task = Task.find(params[:id])
  end
  
  def new
    @task = Task.new
  end
  

  def create
    @task = current_user.tasks.build(task_params)
      
    if @task.save
      flash[:success] = 'Taskが正常に投稿されました'
      redirect_to root_url
    else
      # @tasks = current_user.tasks.order(id: :desc).page(params[:page])
      flash.now[:danger] = 'Taskが投稿されませんでした'
      render :new
    end
  end

  def edit
     
  end

  def update
    if @task.update(task_params)
      flash[:success] = 'Task が正常に更新されました'
      redirect_to root_url
    else
      flash.now[:danger] = 'Task が更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy
    flash[:success] = 'Taskを削除しました。'
    redirect_back(fallback_location: root_path)
  
  end
  
  private
  
 
  def task_params
      params.require(:task).permit(:content, :status)
  end
  
  # 本当にログインユーザが所有しているものかを確認する。
  def correct_user
    # ログインユーザ (current_user) が持つ tasks 限定で検索する。
    # current_user.tasksだけだったら今ログインしているユーザのタスク全て
    @task = current_user.tasks.find_by(id: params[:id])
    # @taskがnilだったら
    unless @task
      redirect_to root_url
    end
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :require_user_logged_in, only: [:index, :show]
  
  # def index
  #   @users = User.order(id: :desc).page(params[:page]).per(25)
  # end

  # def show
  #   @user = User.find(params[:id])
  #   @tasks = @user.tasks.order(id: :desc).page(params[:page])
  #   counts(@user)
  # end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
   <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <a class="navbar-brand" href="/">The Tasklist</a>
    <!-- 横幅が狭い時に出るハンバーガーボタン -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- メニュー項目 -->
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      
    
     <ul class="navbar-nav">
       <% if logged_in? %>
         
          <%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link'  %>

    
      <% else %>    
        <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
        <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        
      <% end %>  
    </ul>      
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>The Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navbar' %>
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="row">
 <div class="col-10">
<%= form_with(model: task, local: true) do |f| %> 
 <% if task.errors.any? %>
    <div id="error_explanation" class="alert alert-warning">
      <ul class="mb-0">
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <%= f.label :content, 'Task' %>
  <%= f.text_field :content, class: 'form-control' %>
</div>  
<div class="form-group">  
   <%= f.label :status, 'Status' %>
  <%= f.text_field :status, class: 'form-control' %>
</div>  

  <%= f.submit 'Post', class: 'btn btn-primary' %>
<% end %>
 </div>
</div>
 

app/views/tasks/_tasks.html.erb
<ul class="list-unstyled">
  <% tasks.each do |task| %>
    <li class="media mb-3">
      <img class="mr-2 rounded" src="<%= gravatar_url(task.user, { size: 50 }) %>" alt="">
      <div class="media-body">
        <div>
          <%= link_to task.user.name, task %> <span class="text-muted">posted at <%= task.created_at %></span>
        </div>
        <div>
          
          <p>Task: <%= task.content %> Status: <%= task.status %></p>
        
        </div>
        
        <!--編集ボタンと削除ボタン-->
        <div>
          <% if current_user == task.user %>
            <%= link_to "Edit", edit_task_path(task) , class: 'btn btn-success btn-sm' %>
            <%= link_to "Delete", task, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %>
           
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
  <%= paginate tasks %>
</ul>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<div class="row">
    <aside class="col-sm-4">
      <%= link_to 'New Task', new_task_path %>
    </aside>
  
  <div class="col-sm-8">
      <%= render 'tasks/tasks', tasks: @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<h1>タスク詳細</h1>

<table class="table table-bordered">
  <tr>
    <th>id</th>
    <td><%= @task.id %></td>
  </tr>
  <tr>
    <th>Task</th>
    <td><%= @task.content %></td>
  </tr>
  <tr>
    <th>Status</th>
    <td><%= @task.status %></td>
  </tr>
</table>

<%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-success btn-sm' %>
<%= link_to 'Delete', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-sm' %>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      <% end %>

<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user, local: true) do |f| %>
  
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

 